adsp_loader_dlkm
audio_pkt_dlkm
audio_prm_dlkm
audpkt_ion_dlkm
aw882xx_dlkm
camera
fs19xx_dlkm
gpr_dlkm
hdmi_dlkm
lpass_cdc_dlkm
lpass_cdc_rx_macro_dlkm
lpass_cdc_tx_macro_dlkm
lpass_cdc_va_macro_dlkm
lpass_cdc_wsa2_macro_dlkm
lpass_cdc_wsa_macro_dlkm
machine_dlkm
mbhc_dlkm
msm-eva
pinctrl_lpi_dlkm
q6_dlkm
q6_notifier_dlkm
q6_pdr_dlkm
snd_event_dlkm
spf_core_dlkm
stub_dlkm
swr_ctrl_dlkm
swr_dlkm
swr_dmic_dlkm
swr_haptics_dlkm
wcd937x_dlkm
wcd937x_slave_dlkm
wcd938x_dlkm
wcd938x_slave_dlkm
wcd9xxx_dlkm
wcd_core_dlkm
wl2868c
wsa881x_dlkm
wsa883x_dlkm
